# .github/workflows/deploy-glue-job.yml
name: Deploy Glue Job

on:
  push:
    branches:
      - main
    paths:
      - 'HealthData_Job/HealthData_Job.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp HealthData_Job/HealthData_Job.py s3://glue-scripts-test2/HealthData_Job.py

      # - name: Update Glue Job
      #   run: |
      #     aws glue update-job \
      #       --job-name HealthData_Job \
      #       --job-update '{
      #         "Role": "arn:aws:iam::393937407710:role/service-role/AWSGlueServiceRole-kube8",
      #         "Command": {
      #           "Name": "glueetl",
      #           "ScriptLocation": "s3://glue-scripts-test2/HealthData_Job.py",
      #           "PythonVersion": "3"
      #         }
      #       }'

